export const mockedData = [
  {
    title: "Title-A",
    start: "Jan 14 2019",
    end: "Jan 23 2019",
    deration: "7 days",
    complete: "42%",
    expanded: true,
    children: [
      {
        title: "SubTitle-A-1",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
        expanded: true,
        children: [{ title: "SubTitle-A-1-1" }],
      },
      {
        title: "SubTitle-A-2",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
        expanded: true,
        children: [{ title: "SubTitle-A-2-1" }],
      },
    ],
  },
  {
    title: "Title-B",
    start: "Jan 14 2019",
    end: "Jan 23 2019",
    deration: "7 days",
    complete: "42%",
    expanded: true,
    children: [
      {
        title: "SubTitle-B-1",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
      },
      {
        title: "SubTitle-B-2",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
      },
    ],
  },
  {
    title: "Title-C",
    start: "Jan 14 2019",
    end: "Jan 23 2019",
    deration: "7 days",
    complete: "42%",
    expanded: true,
    children: [
      {
        title: "SubTitle-C-1",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
      },
      {
        title: "SubTitle-C-2",
        start: "Jan 14 2019",
        end: "Jan 23 2019",
        deration: "7 days",
        complete: "42%",
      },
    ],
  },
];
